// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: analytics.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const aggregatePageViews = `-- name: AggregatePageViews :exec
INSERT INTO daily_stats (date, path, views, visitors)
SELECT
    $1::date,
    path,
    COUNT(*)::int,
    COUNT(DISTINCT visitor_id)::int
FROM page_views
WHERE created_at >= $2::timestamptz AND created_at < $3::timestamptz
  AND NOT is_bot
GROUP BY path
ON CONFLICT (date, path) DO UPDATE
SET views = EXCLUDED.views, visitors = EXCLUDED.visitors
`

type AggregatePageViewsParams struct {
	TargetDate pgtype.Date
	DayStart   pgtype.Timestamptz
	DayEnd     pgtype.Timestamptz
}

func (q *Queries) AggregatePageViews(ctx context.Context, arg AggregatePageViewsParams) error {
	_, err := q.db.Exec(ctx, aggregatePageViews, arg.TargetDate, arg.DayStart, arg.DayEnd)
	return err
}

const aggregateReferrers = `-- name: AggregateReferrers :exec
INSERT INTO daily_referrers (date, referrer_domain, path, hits)
SELECT
    $1::date,
    referrer,
    path,
    COUNT(*)::int
FROM page_views
WHERE created_at >= $2::timestamptz AND created_at < $3::timestamptz
  AND NOT is_bot
  AND referrer != ''
GROUP BY referrer, path
ON CONFLICT (date, referrer_domain, path) DO UPDATE
SET hits = EXCLUDED.hits
`

type AggregateReferrersParams struct {
	TargetDate pgtype.Date
	DayStart   pgtype.Timestamptz
	DayEnd     pgtype.Timestamptz
}

func (q *Queries) AggregateReferrers(ctx context.Context, arg AggregateReferrersParams) error {
	_, err := q.db.Exec(ctx, aggregateReferrers, arg.TargetDate, arg.DayStart, arg.DayEnd)
	return err
}

const aggregateUserStats = `-- name: AggregateUserStats :exec
INSERT INTO daily_user_stats (date, active_users, new_users, new_stories, new_comments)
VALUES (
    $1::date,
    (SELECT COUNT(DISTINCT user_id)::int FROM sessions WHERE last_seen_at >= $2::timestamptz AND last_seen_at < $3::timestamptz),
    (SELECT COUNT(*)::int FROM users WHERE created_at >= $2::timestamptz AND created_at < $3::timestamptz AND deleted_at IS NULL),
    (SELECT COUNT(*)::int FROM stories WHERE created_at >= $2::timestamptz AND created_at < $3::timestamptz AND deleted_at IS NULL),
    (SELECT COUNT(*)::int FROM comments WHERE created_at >= $2::timestamptz AND created_at < $3::timestamptz AND deleted_at IS NULL)
)
ON CONFLICT (date) DO UPDATE
SET active_users = EXCLUDED.active_users,
    new_users = EXCLUDED.new_users,
    new_stories = EXCLUDED.new_stories,
    new_comments = EXCLUDED.new_comments
`

type AggregateUserStatsParams struct {
	TargetDate pgtype.Date
	DayStart   pgtype.Timestamptz
	DayEnd     pgtype.Timestamptz
}

func (q *Queries) AggregateUserStats(ctx context.Context, arg AggregateUserStatsParams) error {
	_, err := q.db.Exec(ctx, aggregateUserStats, arg.TargetDate, arg.DayStart, arg.DayEnd)
	return err
}

const getDailyStatsRange = `-- name: GetDailyStatsRange :many
SELECT
    date,
    SUM(views)::int AS views,
    SUM(visitors)::int AS visitors
FROM daily_stats
WHERE date >= $1::date AND date <= $2::date
GROUP BY date
ORDER BY date
`

type GetDailyStatsRangeParams struct {
	StartDate pgtype.Date
	EndDate   pgtype.Date
}

type GetDailyStatsRangeRow struct {
	Date     pgtype.Date
	Views    int32
	Visitors int32
}

func (q *Queries) GetDailyStatsRange(ctx context.Context, arg GetDailyStatsRangeParams) ([]GetDailyStatsRangeRow, error) {
	rows, err := q.db.Query(ctx, getDailyStatsRange, arg.StartDate, arg.EndDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetDailyStatsRangeRow
	for rows.Next() {
		var i GetDailyStatsRangeRow
		if err := rows.Scan(&i.Date, &i.Views, &i.Visitors); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDailyStatsTotals = `-- name: GetDailyStatsTotals :one
SELECT
    COALESCE(SUM(views), 0)::int AS views,
    COALESCE(SUM(visitors), 0)::int AS visitors
FROM daily_stats
WHERE date >= $1::date AND date <= $2::date
`

type GetDailyStatsTotalsParams struct {
	StartDate pgtype.Date
	EndDate   pgtype.Date
}

type GetDailyStatsTotalsRow struct {
	Views    int32
	Visitors int32
}

func (q *Queries) GetDailyStatsTotals(ctx context.Context, arg GetDailyStatsTotalsParams) (GetDailyStatsTotalsRow, error) {
	row := q.db.QueryRow(ctx, getDailyStatsTotals, arg.StartDate, arg.EndDate)
	var i GetDailyStatsTotalsRow
	err := row.Scan(&i.Views, &i.Visitors)
	return i, err
}

const getDailyUserStatsRange = `-- name: GetDailyUserStatsRange :many
SELECT date, active_users, new_users, new_stories, new_comments
FROM daily_user_stats
WHERE date >= $1::date AND date <= $2::date
ORDER BY date
`

type GetDailyUserStatsRangeParams struct {
	StartDate pgtype.Date
	EndDate   pgtype.Date
}

func (q *Queries) GetDailyUserStatsRange(ctx context.Context, arg GetDailyUserStatsRangeParams) ([]DailyUserStat, error) {
	rows, err := q.db.Query(ctx, getDailyUserStatsRange, arg.StartDate, arg.EndDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DailyUserStat
	for rows.Next() {
		var i DailyUserStat
		if err := rows.Scan(
			&i.Date,
			&i.ActiveUsers,
			&i.NewUsers,
			&i.NewStories,
			&i.NewComments,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLiveBrowserBreakdown = `-- name: GetLiveBrowserBreakdown :many
SELECT
    browser,
    COUNT(*)::int AS count
FROM page_views
WHERE created_at >= $1::timestamptz
  AND NOT is_bot
  AND browser != ''
GROUP BY browser
ORDER BY count DESC
`

type GetLiveBrowserBreakdownRow struct {
	Browser string
	Count   int32
}

func (q *Queries) GetLiveBrowserBreakdown(ctx context.Context, since pgtype.Timestamptz) ([]GetLiveBrowserBreakdownRow, error) {
	rows, err := q.db.Query(ctx, getLiveBrowserBreakdown, since)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetLiveBrowserBreakdownRow
	for rows.Next() {
		var i GetLiveBrowserBreakdownRow
		if err := rows.Scan(&i.Browser, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLiveDeviceBreakdown = `-- name: GetLiveDeviceBreakdown :many
SELECT
    device,
    COUNT(*)::int AS count
FROM page_views
WHERE created_at >= $1::timestamptz
  AND NOT is_bot
  AND device != ''
GROUP BY device
ORDER BY count DESC
`

type GetLiveDeviceBreakdownRow struct {
	Device string
	Count  int32
}

func (q *Queries) GetLiveDeviceBreakdown(ctx context.Context, since pgtype.Timestamptz) ([]GetLiveDeviceBreakdownRow, error) {
	rows, err := q.db.Query(ctx, getLiveDeviceBreakdown, since)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetLiveDeviceBreakdownRow
	for rows.Next() {
		var i GetLiveDeviceBreakdownRow
		if err := rows.Scan(&i.Device, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLiveStats = `-- name: GetLiveStats :one
SELECT
    COUNT(*)::int AS views,
    COUNT(DISTINCT visitor_id)::int AS visitors
FROM page_views
WHERE created_at >= $1::timestamptz
  AND NOT is_bot
`

type GetLiveStatsRow struct {
	Views    int32
	Visitors int32
}

func (q *Queries) GetLiveStats(ctx context.Context, since pgtype.Timestamptz) (GetLiveStatsRow, error) {
	row := q.db.QueryRow(ctx, getLiveStats, since)
	var i GetLiveStatsRow
	err := row.Scan(&i.Views, &i.Visitors)
	return i, err
}

const getLiveTopPages = `-- name: GetLiveTopPages :many
SELECT
    path,
    COUNT(*)::int AS views,
    COUNT(DISTINCT visitor_id)::int AS visitors
FROM page_views
WHERE created_at >= $1::timestamptz
  AND NOT is_bot
GROUP BY path
ORDER BY views DESC
LIMIT $2::int
`

type GetLiveTopPagesParams struct {
	Since      pgtype.Timestamptz
	MaxResults int32
}

type GetLiveTopPagesRow struct {
	Path     string
	Views    int32
	Visitors int32
}

func (q *Queries) GetLiveTopPages(ctx context.Context, arg GetLiveTopPagesParams) ([]GetLiveTopPagesRow, error) {
	rows, err := q.db.Query(ctx, getLiveTopPages, arg.Since, arg.MaxResults)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetLiveTopPagesRow
	for rows.Next() {
		var i GetLiveTopPagesRow
		if err := rows.Scan(&i.Path, &i.Views, &i.Visitors); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLiveTopReferrers = `-- name: GetLiveTopReferrers :many
SELECT
    referrer AS referrer_domain,
    COUNT(*)::int AS hits
FROM page_views
WHERE created_at >= $1::timestamptz
  AND NOT is_bot
  AND referrer != ''
GROUP BY referrer
ORDER BY hits DESC
LIMIT $2::int
`

type GetLiveTopReferrersParams struct {
	Since      pgtype.Timestamptz
	MaxResults int32
}

type GetLiveTopReferrersRow struct {
	ReferrerDomain string
	Hits           int32
}

func (q *Queries) GetLiveTopReferrers(ctx context.Context, arg GetLiveTopReferrersParams) ([]GetLiveTopReferrersRow, error) {
	rows, err := q.db.Query(ctx, getLiveTopReferrers, arg.Since, arg.MaxResults)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetLiveTopReferrersRow
	for rows.Next() {
		var i GetLiveTopReferrersRow
		if err := rows.Scan(&i.ReferrerDomain, &i.Hits); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTopCommenters = `-- name: GetTopCommenters :many
SELECT u.username, COUNT(*)::int AS comments
FROM comments c
JOIN users u ON u.id = c.user_id
WHERE c.created_at >= $1::timestamptz AND c.deleted_at IS NULL
GROUP BY u.username
ORDER BY comments DESC
LIMIT $2::int
`

type GetTopCommentersParams struct {
	Since      pgtype.Timestamptz
	MaxResults int32
}

type GetTopCommentersRow struct {
	Username string
	Comments int32
}

func (q *Queries) GetTopCommenters(ctx context.Context, arg GetTopCommentersParams) ([]GetTopCommentersRow, error) {
	rows, err := q.db.Query(ctx, getTopCommenters, arg.Since, arg.MaxResults)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTopCommentersRow
	for rows.Next() {
		var i GetTopCommentersRow
		if err := rows.Scan(&i.Username, &i.Comments); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTopContributors = `-- name: GetTopContributors :many
SELECT u.username, COUNT(*)::int AS stories
FROM stories s
JOIN users u ON u.id = s.user_id
WHERE s.created_at >= $1::timestamptz AND s.deleted_at IS NULL
GROUP BY u.username
ORDER BY stories DESC
LIMIT $2::int
`

type GetTopContributorsParams struct {
	Since      pgtype.Timestamptz
	MaxResults int32
}

type GetTopContributorsRow struct {
	Username string
	Stories  int32
}

func (q *Queries) GetTopContributors(ctx context.Context, arg GetTopContributorsParams) ([]GetTopContributorsRow, error) {
	rows, err := q.db.Query(ctx, getTopContributors, arg.Since, arg.MaxResults)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTopContributorsRow
	for rows.Next() {
		var i GetTopContributorsRow
		if err := rows.Scan(&i.Username, &i.Stories); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTopPagesRange = `-- name: GetTopPagesRange :many
SELECT
    path,
    SUM(views)::int AS views,
    SUM(visitors)::int AS visitors
FROM daily_stats
WHERE date >= $1::date AND date <= $2::date
GROUP BY path
ORDER BY views DESC
LIMIT $3::int
`

type GetTopPagesRangeParams struct {
	StartDate  pgtype.Date
	EndDate    pgtype.Date
	MaxResults int32
}

type GetTopPagesRangeRow struct {
	Path     string
	Views    int32
	Visitors int32
}

func (q *Queries) GetTopPagesRange(ctx context.Context, arg GetTopPagesRangeParams) ([]GetTopPagesRangeRow, error) {
	rows, err := q.db.Query(ctx, getTopPagesRange, arg.StartDate, arg.EndDate, arg.MaxResults)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTopPagesRangeRow
	for rows.Next() {
		var i GetTopPagesRangeRow
		if err := rows.Scan(&i.Path, &i.Views, &i.Visitors); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTopReferrersRange = `-- name: GetTopReferrersRange :many
SELECT
    referrer_domain,
    SUM(hits)::int AS hits
FROM daily_referrers
WHERE date >= $1::date AND date <= $2::date
GROUP BY referrer_domain
ORDER BY hits DESC
LIMIT $3::int
`

type GetTopReferrersRangeParams struct {
	StartDate  pgtype.Date
	EndDate    pgtype.Date
	MaxResults int32
}

type GetTopReferrersRangeRow struct {
	ReferrerDomain string
	Hits           int32
}

func (q *Queries) GetTopReferrersRange(ctx context.Context, arg GetTopReferrersRangeParams) ([]GetTopReferrersRangeRow, error) {
	rows, err := q.db.Query(ctx, getTopReferrersRange, arg.StartDate, arg.EndDate, arg.MaxResults)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTopReferrersRangeRow
	for rows.Next() {
		var i GetTopReferrersRangeRow
		if err := rows.Scan(&i.ReferrerDomain, &i.Hits); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserActivityStats = `-- name: GetUserActivityStats :one
SELECT
    (SELECT COUNT(DISTINCT user_id)::int FROM sessions WHERE last_seen_at >= $1::timestamptz) AS active_users,
    (SELECT COUNT(*)::int FROM users WHERE created_at >= $1::timestamptz AND deleted_at IS NULL) AS new_users,
    (SELECT COUNT(*)::int FROM stories WHERE created_at >= $1::timestamptz AND deleted_at IS NULL) AS new_stories,
    (SELECT COUNT(*)::int FROM comments WHERE created_at >= $1::timestamptz AND deleted_at IS NULL) AS new_comments
`

type GetUserActivityStatsRow struct {
	ActiveUsers int32
	NewUsers    int32
	NewStories  int32
	NewComments int32
}

func (q *Queries) GetUserActivityStats(ctx context.Context, since pgtype.Timestamptz) (GetUserActivityStatsRow, error) {
	row := q.db.QueryRow(ctx, getUserActivityStats, since)
	var i GetUserActivityStatsRow
	err := row.Scan(
		&i.ActiveUsers,
		&i.NewUsers,
		&i.NewStories,
		&i.NewComments,
	)
	return i, err
}

const insertPageView = `-- name: InsertPageView :exec
INSERT INTO page_views (path, visitor_id, referrer, device, browser, os, is_bot)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type InsertPageViewParams struct {
	Path      string
	VisitorID string
	Referrer  string
	Device    string
	Browser   string
	Os        string
	IsBot     bool
}

func (q *Queries) InsertPageView(ctx context.Context, arg InsertPageViewParams) error {
	_, err := q.db.Exec(ctx, insertPageView,
		arg.Path,
		arg.VisitorID,
		arg.Referrer,
		arg.Device,
		arg.Browser,
		arg.Os,
		arg.IsBot,
	)
	return err
}

const purgePageViews = `-- name: PurgePageViews :execrows
DELETE FROM page_views
WHERE created_at < $1::timestamptz
`

func (q *Queries) PurgePageViews(ctx context.Context, before pgtype.Timestamptz) (int64, error) {
	result, err := q.db.Exec(ctx, purgePageViews, before)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
