// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: api_keys.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAPIKey = `-- name: CreateAPIKey :one
INSERT INTO api_keys (user_id, token_hash, name)
VALUES ($1, $2, $3)
RETURNING id, user_id, token_hash, name, last_used_at, created_at
`

type CreateAPIKeyParams struct {
	UserID    int64
	TokenHash string
	Name      string
}

func (q *Queries) CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) (ApiKey, error) {
	row := q.db.QueryRow(ctx, createAPIKey, arg.UserID, arg.TokenHash, arg.Name)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.Name,
		&i.LastUsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteAPIKey = `-- name: DeleteAPIKey :exec
DELETE FROM api_keys WHERE id = $1 AND user_id = $2
`

type DeleteAPIKeyParams struct {
	ID     int64
	UserID int64
}

func (q *Queries) DeleteAPIKey(ctx context.Context, arg DeleteAPIKeyParams) error {
	_, err := q.db.Exec(ctx, deleteAPIKey, arg.ID, arg.UserID)
	return err
}

const getAPIKeyUserByTokenHash = `-- name: GetAPIKeyUserByTokenHash :one
SELECT
    ak.id AS api_key_id,
    u.id,
    u.username,
    u.email,
    u.password_digest,
    u.is_moderator,
    u.banned_at,
    u.deleted_at,
    u.inviter_id,
    u.campaign,
    u.password_reset_token_hash,
    u.password_reset_token_created_at,
    u.email_confirmed_at,
    u.email_confirmation_token_hash,
    u.email_confirmation_token_created_at,
    u.unconfirmed_email,
    u.website,
    u.about,
    u.created_at,
    u.updated_at
FROM api_keys ak
JOIN users u ON u.id = ak.user_id
WHERE ak.token_hash = $1
`

type GetAPIKeyUserByTokenHashRow struct {
	ApiKeyID                        int64
	ID                              int64
	Username                        string
	Email                           string
	PasswordDigest                  string
	IsModerator                     bool
	BannedAt                        pgtype.Timestamptz
	DeletedAt                       pgtype.Timestamptz
	InviterID                       pgtype.Int8
	Campaign                        string
	PasswordResetTokenHash          pgtype.Text
	PasswordResetTokenCreatedAt     pgtype.Timestamptz
	EmailConfirmedAt                pgtype.Timestamptz
	EmailConfirmationTokenHash      pgtype.Text
	EmailConfirmationTokenCreatedAt pgtype.Timestamptz
	UnconfirmedEmail                pgtype.Text
	Website                         string
	About                           string
	CreatedAt                       pgtype.Timestamptz
	UpdatedAt                       pgtype.Timestamptz
}

func (q *Queries) GetAPIKeyUserByTokenHash(ctx context.Context, tokenHash string) (GetAPIKeyUserByTokenHashRow, error) {
	row := q.db.QueryRow(ctx, getAPIKeyUserByTokenHash, tokenHash)
	var i GetAPIKeyUserByTokenHashRow
	err := row.Scan(
		&i.ApiKeyID,
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordDigest,
		&i.IsModerator,
		&i.BannedAt,
		&i.DeletedAt,
		&i.InviterID,
		&i.Campaign,
		&i.PasswordResetTokenHash,
		&i.PasswordResetTokenCreatedAt,
		&i.EmailConfirmedAt,
		&i.EmailConfirmationTokenHash,
		&i.EmailConfirmationTokenCreatedAt,
		&i.UnconfirmedEmail,
		&i.Website,
		&i.About,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAPIKeysByUserID = `-- name: ListAPIKeysByUserID :many
SELECT id, name, last_used_at, created_at
FROM api_keys
WHERE user_id = $1
ORDER BY created_at DESC
`

type ListAPIKeysByUserIDRow struct {
	ID         int64
	Name       string
	LastUsedAt pgtype.Timestamptz
	CreatedAt  pgtype.Timestamptz
}

func (q *Queries) ListAPIKeysByUserID(ctx context.Context, userID int64) ([]ListAPIKeysByUserIDRow, error) {
	rows, err := q.db.Query(ctx, listAPIKeysByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAPIKeysByUserIDRow
	for rows.Next() {
		var i ListAPIKeysByUserIDRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.LastUsedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const touchAPIKey = `-- name: TouchAPIKey :exec
UPDATE api_keys SET last_used_at = now() WHERE id = $1
`

func (q *Queries) TouchAPIKey(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, touchAPIKey, id)
	return err
}
