// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: campaigns.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCampaign = `-- name: CreateCampaign :one
INSERT INTO campaigns (slug, welcome_message, sponsor_id, created_by_id)
VALUES ($1, $2, $3, $4)
RETURNING id, slug, welcome_message, sponsor_id, created_by_id, active, created_at, updated_at
`

type CreateCampaignParams struct {
	Slug           string
	WelcomeMessage string
	SponsorID      int64
	CreatedByID    int64
}

func (q *Queries) CreateCampaign(ctx context.Context, arg CreateCampaignParams) (Campaign, error) {
	row := q.db.QueryRow(ctx, createCampaign,
		arg.Slug,
		arg.WelcomeMessage,
		arg.SponsorID,
		arg.CreatedByID,
	)
	var i Campaign
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.WelcomeMessage,
		&i.SponsorID,
		&i.CreatedByID,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getActiveCampaignBySlug = `-- name: GetActiveCampaignBySlug :one
SELECT
    c.id, c.slug, c.welcome_message, c.sponsor_id, c.created_by_id, c.active, c.created_at, c.updated_at,
    s.username AS sponsor_name
FROM campaigns c
JOIN users s ON s.id = c.sponsor_id
WHERE lower(c.slug) = lower($1)
  AND c.active = true
LIMIT 1
`

type GetActiveCampaignBySlugRow struct {
	ID             int64
	Slug           string
	WelcomeMessage string
	SponsorID      int64
	CreatedByID    int64
	Active         bool
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
	SponsorName    string
}

func (q *Queries) GetActiveCampaignBySlug(ctx context.Context, slug string) (GetActiveCampaignBySlugRow, error) {
	row := q.db.QueryRow(ctx, getActiveCampaignBySlug, slug)
	var i GetActiveCampaignBySlugRow
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.WelcomeMessage,
		&i.SponsorID,
		&i.CreatedByID,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SponsorName,
	)
	return i, err
}

const listCampaigns = `-- name: ListCampaigns :many
SELECT
    c.id, c.slug, c.welcome_message, c.sponsor_id, c.created_by_id, c.active, c.created_at, c.updated_at,
    s.username AS sponsor_name,
    cb.username AS created_by_name,
    (SELECT count(*) FROM users WHERE campaign = c.slug)::bigint AS registered_count
FROM campaigns c
JOIN users s ON s.id = c.sponsor_id
JOIN users cb ON cb.id = c.created_by_id
ORDER BY c.created_at DESC
`

type ListCampaignsRow struct {
	ID              int64
	Slug            string
	WelcomeMessage  string
	SponsorID       int64
	CreatedByID     int64
	Active          bool
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
	SponsorName     string
	CreatedByName   string
	RegisteredCount int64
}

func (q *Queries) ListCampaigns(ctx context.Context) ([]ListCampaignsRow, error) {
	rows, err := q.db.Query(ctx, listCampaigns)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCampaignsRow
	for rows.Next() {
		var i ListCampaignsRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.WelcomeMessage,
			&i.SponsorID,
			&i.CreatedByID,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SponsorName,
			&i.CreatedByName,
			&i.RegisteredCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setCampaignActive = `-- name: SetCampaignActive :exec
UPDATE campaigns
SET active = $1, updated_at = now()
WHERE id = $2
`

type SetCampaignActiveParams struct {
	Active bool
	ID     int64
}

func (q *Queries) SetCampaignActive(ctx context.Context, arg SetCampaignActiveParams) error {
	_, err := q.db.Exec(ctx, setCampaignActive, arg.Active, arg.ID)
	return err
}
