// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: comment_votes.sql

package store

import (
	"context"
)

const createCommentVote = `-- name: CreateCommentVote :one
WITH ins AS (
    INSERT INTO comment_votes (user_id, comment_id)
    VALUES ($2, $1)
    ON CONFLICT DO NOTHING
    RETURNING comment_id
)
UPDATE comments SET upvotes = upvotes + (SELECT count(*) FROM ins)::int
WHERE id = $1
RETURNING upvotes - downvotes AS score
`

type CreateCommentVoteParams struct {
	CommentID int64
	UserID    int64
}

func (q *Queries) CreateCommentVote(ctx context.Context, arg CreateCommentVoteParams) (int32, error) {
	row := q.db.QueryRow(ctx, createCommentVote, arg.CommentID, arg.UserID)
	var score int32
	err := row.Scan(&score)
	return score, err
}

const deleteCommentVote = `-- name: DeleteCommentVote :one
WITH del AS (
    DELETE FROM comment_votes
    WHERE comment_votes.user_id = $2 AND comment_votes.comment_id = $1
    RETURNING comment_id
)
UPDATE comments SET upvotes = upvotes - (SELECT count(*) FROM del)::int
WHERE id = $1
RETURNING upvotes - downvotes AS score
`

type DeleteCommentVoteParams struct {
	CommentID int64
	UserID    int64
}

func (q *Queries) DeleteCommentVote(ctx context.Context, arg DeleteCommentVoteParams) (int32, error) {
	row := q.db.QueryRow(ctx, deleteCommentVote, arg.CommentID, arg.UserID)
	var score int32
	err := row.Scan(&score)
	return score, err
}

const getUserCommentVotes = `-- name: GetUserCommentVotes :many
SELECT comment_id
FROM comment_votes
WHERE user_id = $1 AND comment_id = ANY($2::bigint[])
`

type GetUserCommentVotesParams struct {
	UserID     int64
	CommentIds []int64
}

func (q *Queries) GetUserCommentVotes(ctx context.Context, arg GetUserCommentVotesParams) ([]int64, error) {
	rows, err := q.db.Query(ctx, getUserCommentVotes, arg.UserID, arg.CommentIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var comment_id int64
		if err := rows.Scan(&comment_id); err != nil {
			return nil, err
		}
		items = append(items, comment_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
