// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: comment_flags.sql

package store

import (
	"context"
)

const createCommentFlag = `-- name: CreateCommentFlag :one
WITH ins AS (
    INSERT INTO comment_flags (user_id, comment_id, reason)
    VALUES ($2, $1, $3)
    ON CONFLICT DO NOTHING
    RETURNING comment_id
)
UPDATE comments SET downvotes = downvotes + (SELECT count(*) FROM ins)::int
WHERE id = $1
RETURNING upvotes - downvotes AS score
`

type CreateCommentFlagParams struct {
	CommentID int64
	UserID    int64
	Reason    string
}

func (q *Queries) CreateCommentFlag(ctx context.Context, arg CreateCommentFlagParams) (int32, error) {
	row := q.db.QueryRow(ctx, createCommentFlag, arg.CommentID, arg.UserID, arg.Reason)
	var score int32
	err := row.Scan(&score)
	return score, err
}

const deleteCommentFlag = `-- name: DeleteCommentFlag :one
WITH del AS (
    DELETE FROM comment_flags
    WHERE comment_flags.user_id = $2 AND comment_flags.comment_id = $1
    RETURNING comment_id
)
UPDATE comments SET downvotes = downvotes - (SELECT count(*) FROM del)::int
WHERE id = $1
RETURNING upvotes - downvotes AS score
`

type DeleteCommentFlagParams struct {
	CommentID int64
	UserID    int64
}

func (q *Queries) DeleteCommentFlag(ctx context.Context, arg DeleteCommentFlagParams) (int32, error) {
	row := q.db.QueryRow(ctx, deleteCommentFlag, arg.CommentID, arg.UserID)
	var score int32
	err := row.Scan(&score)
	return score, err
}

const getCommentFlagCounts = `-- name: GetCommentFlagCounts :many
SELECT comment_id, reason, count(*)::int AS count
FROM comment_flags
WHERE comment_id = ANY($1::bigint[])
GROUP BY comment_id, reason
ORDER BY comment_id, count DESC
`

type GetCommentFlagCountsRow struct {
	CommentID int64
	Reason    string
	Count     int32
}

func (q *Queries) GetCommentFlagCounts(ctx context.Context, commentIds []int64) ([]GetCommentFlagCountsRow, error) {
	rows, err := q.db.Query(ctx, getCommentFlagCounts, commentIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCommentFlagCountsRow
	for rows.Next() {
		var i GetCommentFlagCountsRow
		if err := rows.Scan(&i.CommentID, &i.Reason, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserCommentFlags = `-- name: GetUserCommentFlags :many
SELECT comment_id
FROM comment_flags
WHERE user_id = $1 AND comment_id = ANY($2::bigint[])
`

type GetUserCommentFlagsParams struct {
	UserID     int64
	CommentIds []int64
}

func (q *Queries) GetUserCommentFlags(ctx context.Context, arg GetUserCommentFlagsParams) ([]int64, error) {
	rows, err := q.db.Query(ctx, getUserCommentFlags, arg.UserID, arg.CommentIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var comment_id int64
		if err := rows.Scan(&comment_id); err != nil {
			return nil, err
		}
		items = append(items, comment_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
