// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: comments.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createComment = `-- name: CreateComment :one
INSERT INTO comments (story_id, user_id, parent_id, body, depth)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, story_id, user_id, parent_id, body, depth, upvotes, downvotes, created_at, updated_at, deleted_at
`

type CreateCommentParams struct {
	StoryID  int64
	UserID   int64
	ParentID pgtype.Int8
	Body     string
	Depth    int32
}

func (q *Queries) CreateComment(ctx context.Context, arg CreateCommentParams) (Comment, error) {
	row := q.db.QueryRow(ctx, createComment,
		arg.StoryID,
		arg.UserID,
		arg.ParentID,
		arg.Body,
		arg.Depth,
	)
	var i Comment
	err := row.Scan(
		&i.ID,
		&i.StoryID,
		&i.UserID,
		&i.ParentID,
		&i.Body,
		&i.Depth,
		&i.Upvotes,
		&i.Downvotes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const decrementStoryCommentCount = `-- name: DecrementStoryCommentCount :exec
UPDATE stories SET comment_count = comment_count - 1 WHERE id = $1 AND comment_count > 0
`

func (q *Queries) DecrementStoryCommentCount(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, decrementStoryCommentCount, id)
	return err
}

const getCommentByID = `-- name: GetCommentByID :one
SELECT id, story_id, user_id, parent_id, body, depth, upvotes, downvotes, created_at, updated_at, deleted_at
FROM comments
WHERE id = $1
`

func (q *Queries) GetCommentByID(ctx context.Context, id int64) (Comment, error) {
	row := q.db.QueryRow(ctx, getCommentByID, id)
	var i Comment
	err := row.Scan(
		&i.ID,
		&i.StoryID,
		&i.UserID,
		&i.ParentID,
		&i.Body,
		&i.Depth,
		&i.Upvotes,
		&i.Downvotes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getCommentDepth = `-- name: GetCommentDepth :one
SELECT depth FROM comments WHERE id = $1
`

func (q *Queries) GetCommentDepth(ctx context.Context, id int64) (int32, error) {
	row := q.db.QueryRow(ctx, getCommentDepth, id)
	var depth int32
	err := row.Scan(&depth)
	return depth, err
}

const getCommentRankingDataByStories = `-- name: GetCommentRankingDataByStories :many
SELECT
    c.story_id,
    count(*)::int AS total,
    count(*) FILTER (WHERE c.user_id = s.user_id)::int AS by_submitter
FROM comments c
JOIN stories s ON s.id = c.story_id
WHERE c.story_id = ANY($1::bigint[])
  AND c.deleted_at IS NULL
GROUP BY c.story_id
`

type GetCommentRankingDataByStoriesRow struct {
	StoryID     int64
	Total       int32
	BySubmitter int32
}

func (q *Queries) GetCommentRankingDataByStories(ctx context.Context, storyIds []int64) ([]GetCommentRankingDataByStoriesRow, error) {
	rows, err := q.db.Query(ctx, getCommentRankingDataByStories, storyIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCommentRankingDataByStoriesRow
	for rows.Next() {
		var i GetCommentRankingDataByStoriesRow
		if err := rows.Scan(&i.StoryID, &i.Total, &i.BySubmitter); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const incrementStoryCommentCount = `-- name: IncrementStoryCommentCount :exec
UPDATE stories SET comment_count = comment_count + 1 WHERE id = $1
`

func (q *Queries) IncrementStoryCommentCount(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, incrementStoryCommentCount, id)
	return err
}

const listCommentsByStory = `-- name: ListCommentsByStory :many
SELECT
    c.id,
    c.story_id,
    c.user_id,
    c.parent_id,
    c.body,
    c.depth,
    c.upvotes,
    c.downvotes,
    c.created_at,
    c.updated_at,
    c.deleted_at,
    u.username
FROM comments AS c
JOIN users AS u ON u.id = c.user_id
WHERE c.story_id = $1
ORDER BY c.created_at ASC
`

type ListCommentsByStoryRow struct {
	ID        int64
	StoryID   int64
	UserID    int64
	ParentID  pgtype.Int8
	Body      string
	Depth     int32
	Upvotes   int32
	Downvotes int32
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	DeletedAt pgtype.Timestamptz
	Username  string
}

func (q *Queries) ListCommentsByStory(ctx context.Context, storyID int64) ([]ListCommentsByStoryRow, error) {
	rows, err := q.db.Query(ctx, listCommentsByStory, storyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCommentsByStoryRow
	for rows.Next() {
		var i ListCommentsByStoryRow
		if err := rows.Scan(
			&i.ID,
			&i.StoryID,
			&i.UserID,
			&i.ParentID,
			&i.Body,
			&i.Depth,
			&i.Upvotes,
			&i.Downvotes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.Username,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteComment = `-- name: SoftDeleteComment :exec
UPDATE comments SET deleted_at = now(), body = ''
WHERE id = $1
`

func (q *Queries) SoftDeleteComment(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, softDeleteComment, id)
	return err
}

const updateCommentBody = `-- name: UpdateCommentBody :exec
UPDATE comments SET body = $1, updated_at = now()
WHERE id = $2
`

type UpdateCommentBodyParams struct {
	Body string
	ID   int64
}

func (q *Queries) UpdateCommentBody(ctx context.Context, arg UpdateCommentBodyParams) error {
	_, err := q.db.Exec(ctx, updateCommentBody, arg.Body, arg.ID)
	return err
}
