// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: comments.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createComment = `-- name: CreateComment :one
INSERT INTO comments (story_id, user_id, parent_id, body, depth, short_code)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, story_id, user_id, parent_id, body, depth, short_code, upvotes, downvotes, created_at, updated_at, deleted_at
`

type CreateCommentParams struct {
	StoryID   int64
	UserID    int64
	ParentID  pgtype.Int8
	Body      string
	Depth     int32
	ShortCode string
}

type CreateCommentRow struct {
	ID        int64
	StoryID   int64
	UserID    int64
	ParentID  pgtype.Int8
	Body      string
	Depth     int32
	ShortCode string
	Upvotes   int32
	Downvotes int32
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	DeletedAt pgtype.Timestamptz
}

func (q *Queries) CreateComment(ctx context.Context, arg CreateCommentParams) (CreateCommentRow, error) {
	row := q.db.QueryRow(ctx, createComment,
		arg.StoryID,
		arg.UserID,
		arg.ParentID,
		arg.Body,
		arg.Depth,
		arg.ShortCode,
	)
	var i CreateCommentRow
	err := row.Scan(
		&i.ID,
		&i.StoryID,
		&i.UserID,
		&i.ParentID,
		&i.Body,
		&i.Depth,
		&i.ShortCode,
		&i.Upvotes,
		&i.Downvotes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const decrementStoryCommentCount = `-- name: DecrementStoryCommentCount :exec
UPDATE stories SET comment_count = comment_count - 1 WHERE id = $1 AND comment_count > 0
`

func (q *Queries) DecrementStoryCommentCount(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, decrementStoryCommentCount, id)
	return err
}

const getCommentByID = `-- name: GetCommentByID :one
SELECT id, story_id, user_id, parent_id, body, depth, short_code, upvotes, downvotes, created_at, updated_at, deleted_at
FROM comments
WHERE id = $1
`

type GetCommentByIDRow struct {
	ID        int64
	StoryID   int64
	UserID    int64
	ParentID  pgtype.Int8
	Body      string
	Depth     int32
	ShortCode string
	Upvotes   int32
	Downvotes int32
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	DeletedAt pgtype.Timestamptz
}

func (q *Queries) GetCommentByID(ctx context.Context, id int64) (GetCommentByIDRow, error) {
	row := q.db.QueryRow(ctx, getCommentByID, id)
	var i GetCommentByIDRow
	err := row.Scan(
		&i.ID,
		&i.StoryID,
		&i.UserID,
		&i.ParentID,
		&i.Body,
		&i.Depth,
		&i.ShortCode,
		&i.Upvotes,
		&i.Downvotes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getCommentByShortCode = `-- name: GetCommentByShortCode :one
SELECT id, story_id, user_id, parent_id, body, depth, short_code, upvotes, downvotes, created_at, updated_at, deleted_at
FROM comments
WHERE short_code = $1
`

type GetCommentByShortCodeRow struct {
	ID        int64
	StoryID   int64
	UserID    int64
	ParentID  pgtype.Int8
	Body      string
	Depth     int32
	ShortCode string
	Upvotes   int32
	Downvotes int32
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	DeletedAt pgtype.Timestamptz
}

func (q *Queries) GetCommentByShortCode(ctx context.Context, shortCode string) (GetCommentByShortCodeRow, error) {
	row := q.db.QueryRow(ctx, getCommentByShortCode, shortCode)
	var i GetCommentByShortCodeRow
	err := row.Scan(
		&i.ID,
		&i.StoryID,
		&i.UserID,
		&i.ParentID,
		&i.Body,
		&i.Depth,
		&i.ShortCode,
		&i.Upvotes,
		&i.Downvotes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const incrementStoryCommentCount = `-- name: IncrementStoryCommentCount :exec
UPDATE stories SET comment_count = comment_count + 1 WHERE id = $1
`

func (q *Queries) IncrementStoryCommentCount(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, incrementStoryCommentCount, id)
	return err
}

const listCommentsByStory = `-- name: ListCommentsByStory :many
SELECT
    c.id,
    c.story_id,
    c.user_id,
    c.parent_id,
    c.body,
    c.depth,
    c.short_code,
    c.upvotes,
    c.downvotes,
    c.created_at,
    c.updated_at,
    c.deleted_at,
    u.username
FROM comments AS c
JOIN users AS u ON u.id = c.user_id
WHERE c.story_id = $1
ORDER BY c.created_at ASC
`

type ListCommentsByStoryRow struct {
	ID        int64
	StoryID   int64
	UserID    int64
	ParentID  pgtype.Int8
	Body      string
	Depth     int32
	ShortCode string
	Upvotes   int32
	Downvotes int32
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	DeletedAt pgtype.Timestamptz
	Username  string
}

func (q *Queries) ListCommentsByStory(ctx context.Context, storyID int64) ([]ListCommentsByStoryRow, error) {
	rows, err := q.db.Query(ctx, listCommentsByStory, storyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCommentsByStoryRow
	for rows.Next() {
		var i ListCommentsByStoryRow
		if err := rows.Scan(
			&i.ID,
			&i.StoryID,
			&i.UserID,
			&i.ParentID,
			&i.Body,
			&i.Depth,
			&i.ShortCode,
			&i.Upvotes,
			&i.Downvotes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.Username,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCommentsByStoryCode = `-- name: ListCommentsByStoryCode :many
SELECT
    c.short_code,
    c.body,
    c.depth,
    c.upvotes,
    c.downvotes,
    c.created_at,
    c.deleted_at,
    u.username,
    p.short_code AS parent_short_code
FROM comments AS c
JOIN users AS u ON u.id = c.user_id
LEFT JOIN comments AS p ON p.id = c.parent_id
JOIN stories AS s ON s.id = c.story_id
WHERE s.short_code = $1
ORDER BY c.created_at ASC
`

type ListCommentsByStoryCodeRow struct {
	ShortCode       string
	Body            string
	Depth           int32
	Upvotes         int32
	Downvotes       int32
	CreatedAt       pgtype.Timestamptz
	DeletedAt       pgtype.Timestamptz
	Username        string
	ParentShortCode pgtype.Text
}

func (q *Queries) ListCommentsByStoryCode(ctx context.Context, storyShortCode string) ([]ListCommentsByStoryCodeRow, error) {
	rows, err := q.db.Query(ctx, listCommentsByStoryCode, storyShortCode)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCommentsByStoryCodeRow
	for rows.Next() {
		var i ListCommentsByStoryCodeRow
		if err := rows.Scan(
			&i.ShortCode,
			&i.Body,
			&i.Depth,
			&i.Upvotes,
			&i.Downvotes,
			&i.CreatedAt,
			&i.DeletedAt,
			&i.Username,
			&i.ParentShortCode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteComment = `-- name: SoftDeleteComment :exec
UPDATE comments SET deleted_at = now(), body = ''
WHERE id = $1
`

func (q *Queries) SoftDeleteComment(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, softDeleteComment, id)
	return err
}

const storyExistsByCode = `-- name: StoryExistsByCode :one
SELECT EXISTS(SELECT 1 FROM stories WHERE short_code = $1 AND deleted_at IS NULL) AS exists
`

func (q *Queries) StoryExistsByCode(ctx context.Context, shortCode string) (bool, error) {
	row := q.db.QueryRow(ctx, storyExistsByCode, shortCode)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const updateCommentBody = `-- name: UpdateCommentBody :exec
UPDATE comments SET body = $1, updated_at = now()
WHERE id = $2
`

type UpdateCommentBodyParams struct {
	Body string
	ID   int64
}

func (q *Queries) UpdateCommentBody(ctx context.Context, arg UpdateCommentBodyParams) error {
	_, err := q.db.Exec(ctx, updateCommentBody, arg.Body, arg.ID)
	return err
}
