// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: domains.sql

package store

import (
	"context"
)

const createDomain = `-- name: CreateDomain :one
INSERT INTO domains (domain)
VALUES ($1)
RETURNING id, domain, banned, ban_reason, story_count, created_at, updated_at
`

func (q *Queries) CreateDomain(ctx context.Context, domain string) (Domain, error) {
	row := q.db.QueryRow(ctx, createDomain, domain)
	var i Domain
	err := row.Scan(
		&i.ID,
		&i.Domain,
		&i.Banned,
		&i.BanReason,
		&i.StoryCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDomainByName = `-- name: GetDomainByName :one
SELECT id, domain, banned, ban_reason, story_count, created_at, updated_at
FROM domains
WHERE lower(domain) = lower($1)
LIMIT 1
`

func (q *Queries) GetDomainByName(ctx context.Context, domain string) (Domain, error) {
	row := q.db.QueryRow(ctx, getDomainByName, domain)
	var i Domain
	err := row.Scan(
		&i.ID,
		&i.Domain,
		&i.Banned,
		&i.BanReason,
		&i.StoryCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const incrementDomainStoryCount = `-- name: IncrementDomainStoryCount :exec
UPDATE domains
SET story_count = story_count + 1, updated_at = now()
WHERE id = $1
`

func (q *Queries) IncrementDomainStoryCount(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, incrementDomainStoryCount, id)
	return err
}
