// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: domains.sql

package store

import (
	"context"
)

const getOrCreateDomain = `-- name: GetOrCreateDomain :one
INSERT INTO domains (domain)
VALUES ($1)
ON CONFLICT ((lower(domain))) DO UPDATE SET domain = domains.domain
RETURNING id, domain, banned, ban_reason, story_count, created_at, updated_at
`

func (q *Queries) GetOrCreateDomain(ctx context.Context, domain string) (Domain, error) {
	row := q.db.QueryRow(ctx, getOrCreateDomain, domain)
	var i Domain
	err := row.Scan(
		&i.ID,
		&i.Domain,
		&i.Banned,
		&i.BanReason,
		&i.StoryCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const incrementDomainStoryCount = `-- name: IncrementDomainStoryCount :exec
UPDATE domains
SET story_count = story_count + 1, updated_at = now()
WHERE id = $1
`

func (q *Queries) IncrementDomainStoryCount(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, incrementDomainStoryCount, id)
	return err
}
