// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: hidden_stories.sql

package store

import (
	"context"
)

const getUserHiddenStories = `-- name: GetUserHiddenStories :many
SELECT story_id
FROM hidden_stories
WHERE user_id = $1 AND story_id = ANY($2::bigint[])
`

type GetUserHiddenStoriesParams struct {
	UserID   int64
	StoryIds []int64
}

func (q *Queries) GetUserHiddenStories(ctx context.Context, arg GetUserHiddenStoriesParams) ([]int64, error) {
	rows, err := q.db.Query(ctx, getUserHiddenStories, arg.UserID, arg.StoryIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var story_id int64
		if err := rows.Scan(&story_id); err != nil {
			return nil, err
		}
		items = append(items, story_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const hideStory = `-- name: HideStory :exec
INSERT INTO hidden_stories (user_id, story_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type HideStoryParams struct {
	UserID  int64
	StoryID int64
}

func (q *Queries) HideStory(ctx context.Context, arg HideStoryParams) error {
	_, err := q.db.Exec(ctx, hideStory, arg.UserID, arg.StoryID)
	return err
}

const unhideStory = `-- name: UnhideStory :exec
DELETE FROM hidden_stories
WHERE user_id = $1 AND story_id = $2
`

type UnhideStoryParams struct {
	UserID  int64
	StoryID int64
}

func (q *Queries) UnhideStory(ctx context.Context, arg UnhideStoryParams) error {
	_, err := q.db.Exec(ctx, unhideStory, arg.UserID, arg.StoryID)
	return err
}
