// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: hidden_tags.sql

package store

import (
	"context"
)

const hideTag = `-- name: HideTag :exec
INSERT INTO hidden_tags (user_id, tag_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type HideTagParams struct {
	UserID int64
	TagID  int64
}

func (q *Queries) HideTag(ctx context.Context, arg HideTagParams) error {
	_, err := q.db.Exec(ctx, hideTag, arg.UserID, arg.TagID)
	return err
}

const listUserHiddenTagIDs = `-- name: ListUserHiddenTagIDs :many
SELECT tag_id FROM hidden_tags WHERE user_id = $1
`

func (q *Queries) ListUserHiddenTagIDs(ctx context.Context, userID int64) ([]int64, error) {
	rows, err := q.db.Query(ctx, listUserHiddenTagIDs, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var tag_id int64
		if err := rows.Scan(&tag_id); err != nil {
			return nil, err
		}
		items = append(items, tag_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const unhideTag = `-- name: UnhideTag :exec
DELETE FROM hidden_tags
WHERE user_id = $1 AND tag_id = $2
`

type UnhideTagParams struct {
	UserID int64
	TagID  int64
}

func (q *Queries) UnhideTag(ctx context.Context, arg UnhideTagParams) error {
	_, err := q.db.Exec(ctx, unhideTag, arg.UserID, arg.TagID)
	return err
}
