// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: invitations.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimInvitation = `-- name: ClaimInvitation :one
UPDATE invitations
SET used_by_id = $1
WHERE id = $2 AND used_by_id IS NULL
RETURNING id
`

type ClaimInvitationParams struct {
	UsedByID pgtype.Int8
	ID       int64
}

func (q *Queries) ClaimInvitation(ctx context.Context, arg ClaimInvitationParams) (int64, error) {
	row := q.db.QueryRow(ctx, claimInvitation, arg.UsedByID, arg.ID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const createInvitation = `-- name: CreateInvitation :one
INSERT INTO invitations (inviter_id, email, token_hash)
VALUES ($1, $2, $3)
RETURNING id, inviter_id, email, token_hash, used_by_id, created_at
`

type CreateInvitationParams struct {
	InviterID int64
	Email     pgtype.Text
	TokenHash string
}

func (q *Queries) CreateInvitation(ctx context.Context, arg CreateInvitationParams) (Invitation, error) {
	row := q.db.QueryRow(ctx, createInvitation, arg.InviterID, arg.Email, arg.TokenHash)
	var i Invitation
	err := row.Scan(
		&i.ID,
		&i.InviterID,
		&i.Email,
		&i.TokenHash,
		&i.UsedByID,
		&i.CreatedAt,
	)
	return i, err
}

const getInvitationByTokenHash = `-- name: GetInvitationByTokenHash :one
SELECT
    i.id,
    i.inviter_id,
    i.email,
    i.used_by_id,
    i.created_at,
    u.username AS inviter_name
FROM invitations i
JOIN users u ON u.id = i.inviter_id
WHERE i.token_hash = $1
  AND i.used_by_id IS NULL
  AND i.created_at > now() - INTERVAL '24 hours'
`

type GetInvitationByTokenHashRow struct {
	ID          int64
	InviterID   int64
	Email       pgtype.Text
	UsedByID    pgtype.Int8
	CreatedAt   pgtype.Timestamptz
	InviterName string
}

func (q *Queries) GetInvitationByTokenHash(ctx context.Context, tokenHash string) (GetInvitationByTokenHashRow, error) {
	row := q.db.QueryRow(ctx, getInvitationByTokenHash, tokenHash)
	var i GetInvitationByTokenHashRow
	err := row.Scan(
		&i.ID,
		&i.InviterID,
		&i.Email,
		&i.UsedByID,
		&i.CreatedAt,
		&i.InviterName,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, username, email
FROM users
WHERE lower(email) = lower($1)
LIMIT 1
`

type GetUserByEmailRow struct {
	ID       int64
	Username string
	Email    string
}

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i GetUserByEmailRow
	err := row.Scan(&i.ID, &i.Username, &i.Email)
	return i, err
}

const listInvitationsByUser = `-- name: ListInvitationsByUser :many
SELECT
    i.id,
    i.email,
    i.used_by_id,
    i.created_at,
    ru.username AS registered_username
FROM invitations i
LEFT JOIN users ru ON ru.id = i.used_by_id
WHERE i.inviter_id = $1
ORDER BY i.created_at DESC
LIMIT 20
`

type ListInvitationsByUserRow struct {
	ID                 int64
	Email              pgtype.Text
	UsedByID           pgtype.Int8
	CreatedAt          pgtype.Timestamptz
	RegisteredUsername pgtype.Text
}

func (q *Queries) ListInvitationsByUser(ctx context.Context, inviterID int64) ([]ListInvitationsByUserRow, error) {
	rows, err := q.db.Query(ctx, listInvitationsByUser, inviterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListInvitationsByUserRow
	for rows.Next() {
		var i ListInvitationsByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.UsedByID,
			&i.CreatedAt,
			&i.RegisteredUsername,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
