// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package store

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Campaign struct {
	ID             int64
	Slug           string
	WelcomeMessage string
	SponsorID      int64
	CreatedByID    int64
	Active         bool
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

type Category struct {
	ID        int64
	Name      string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type Comment struct {
	ID        int64
	StoryID   int64
	UserID    int64
	ParentID  pgtype.Int8
	Body      string
	Depth     int32
	Upvotes   int32
	Downvotes int32
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	DeletedAt pgtype.Timestamptz
}

type CommentFlag struct {
	UserID    int64
	CommentID int64
	Reason    string
	CreatedAt pgtype.Timestamptz
}

type CommentVote struct {
	UserID    int64
	CommentID int64
	CreatedAt pgtype.Timestamptz
}

type Domain struct {
	ID         int64
	Domain     string
	Banned     bool
	BanReason  string
	StoryCount int32
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
}

type HiddenStory struct {
	UserID    int64
	StoryID   int64
	CreatedAt pgtype.Timestamptz
}

type HiddenTag struct {
	UserID int64
	TagID  int64
}

type Invitation struct {
	ID        int64
	InviterID int64
	Email     pgtype.Text
	TokenHash string
	UsedByID  pgtype.Int8
	CreatedAt pgtype.Timestamptz
}

type Origin struct {
	ID         int64
	DomainID   int64
	Origin     string
	Banned     bool
	BanReason  string
	StoryCount int32
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
}

type Session struct {
	ID         int64
	UserID     int64
	TokenHash  string
	UserAgent  string
	IpAddress  string
	ExpiresAt  pgtype.Timestamptz
	LastSeenAt pgtype.Timestamptz
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
}

type Story struct {
	ID            int64
	UserID        int64
	DomainID      pgtype.Int8
	OriginID      pgtype.Int8
	Url           pgtype.Text
	NormalizedUrl pgtype.Text
	Title         string
	Body          pgtype.Text
	ShortCode     string
	Upvotes       int32
	Downvotes     int32
	CommentCount  int32
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
	DeletedAt     pgtype.Timestamptz
}

type StoryFlag struct {
	UserID    int64
	StoryID   int64
	Reason    string
	CreatedAt pgtype.Timestamptz
}

type StoryVisit struct {
	UserID     int64
	StoryID    int64
	LastSeenAt pgtype.Timestamptz
}

type Tag struct {
	ID          int64
	Tag         string
	Description string
	CategoryID  pgtype.Int8
	Privileged  bool
	IsMedia     bool
	Active      bool
	HotnessMod  float64
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type Tagging struct {
	StoryID int64
	TagID   int64
}

type User struct {
	ID                              int64
	Username                        string
	Email                           string
	PasswordDigest                  string
	IsModerator                     bool
	BannedAt                        pgtype.Timestamptz
	DeletedAt                       pgtype.Timestamptz
	InviterID                       pgtype.Int8
	Campaign                        string
	PasswordResetTokenHash          pgtype.Text
	PasswordResetTokenCreatedAt     pgtype.Timestamptz
	EmailConfirmedAt                pgtype.Timestamptz
	EmailConfirmationTokenHash      pgtype.Text
	EmailConfirmationTokenCreatedAt pgtype.Timestamptz
	UnconfirmedEmail                pgtype.Text
	Website                         string
	About                           string
	CreatedAt                       pgtype.Timestamptz
	UpdatedAt                       pgtype.Timestamptz
}

type Vote struct {
	UserID    int64
	StoryID   int64
	CreatedAt pgtype.Timestamptz
}
