// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: origins.sql

package store

import (
	"context"
)

const createOrigin = `-- name: CreateOrigin :one
INSERT INTO origins (domain_id, origin)
VALUES ($1, $2)
RETURNING id, domain_id, origin, banned, ban_reason, story_count, created_at, updated_at
`

type CreateOriginParams struct {
	DomainID int64
	Origin   string
}

func (q *Queries) CreateOrigin(ctx context.Context, arg CreateOriginParams) (Origin, error) {
	row := q.db.QueryRow(ctx, createOrigin, arg.DomainID, arg.Origin)
	var i Origin
	err := row.Scan(
		&i.ID,
		&i.DomainID,
		&i.Origin,
		&i.Banned,
		&i.BanReason,
		&i.StoryCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOriginByName = `-- name: GetOriginByName :one
SELECT id, domain_id, origin, banned, ban_reason, story_count, created_at, updated_at
FROM origins
WHERE lower(origin) = lower($1)
LIMIT 1
`

func (q *Queries) GetOriginByName(ctx context.Context, origin string) (Origin, error) {
	row := q.db.QueryRow(ctx, getOriginByName, origin)
	var i Origin
	err := row.Scan(
		&i.ID,
		&i.DomainID,
		&i.Origin,
		&i.Banned,
		&i.BanReason,
		&i.StoryCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const incrementOriginStoryCount = `-- name: IncrementOriginStoryCount :exec
UPDATE origins
SET story_count = story_count + 1, updated_at = now()
WHERE id = $1
`

func (q *Queries) IncrementOriginStoryCount(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, incrementOriginStoryCount, id)
	return err
}
