// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: stats.sql

package store

import (
	"context"
)

const getSiteStats = `-- name: GetSiteStats :one
SELECT
    (SELECT count(*) FROM users WHERE banned_at IS NULL AND deleted_at IS NULL)::bigint AS total_users,
    (SELECT count(*) FROM users WHERE created_at >= CURRENT_DATE AND banned_at IS NULL AND deleted_at IS NULL)::bigint AS users_today,
    (SELECT count(*) FROM users WHERE created_at >= CURRENT_DATE - INTERVAL '7 days' AND banned_at IS NULL AND deleted_at IS NULL)::bigint AS users_this_week,
    (SELECT count(*) FROM stories WHERE deleted_at IS NULL)::bigint AS total_stories,
    (SELECT count(*) FROM stories WHERE created_at >= CURRENT_DATE AND deleted_at IS NULL)::bigint AS stories_today,
    (SELECT count(*) FROM stories WHERE created_at >= CURRENT_DATE - INTERVAL '7 days' AND deleted_at IS NULL)::bigint AS stories_this_week,
    (SELECT count(*) FROM comments WHERE deleted_at IS NULL)::bigint AS total_comments,
    (SELECT count(*) FROM comments WHERE created_at >= CURRENT_DATE AND deleted_at IS NULL)::bigint AS comments_today,
    (SELECT count(*) FROM comments WHERE created_at >= CURRENT_DATE - INTERVAL '7 days' AND deleted_at IS NULL)::bigint AS comments_this_week,
    (SELECT count(DISTINCT user_id) FROM sessions WHERE last_seen_at >= CURRENT_DATE AND expires_at > now())::bigint AS active_users_today,
    (SELECT count(DISTINCT user_id) FROM sessions WHERE last_seen_at >= CURRENT_DATE - INTERVAL '7 days' AND expires_at > now())::bigint AS active_users_this_week
`

type GetSiteStatsRow struct {
	TotalUsers          int64
	UsersToday          int64
	UsersThisWeek       int64
	TotalStories        int64
	StoriesToday        int64
	StoriesThisWeek     int64
	TotalComments       int64
	CommentsToday       int64
	CommentsThisWeek    int64
	ActiveUsersToday    int64
	ActiveUsersThisWeek int64
}

func (q *Queries) GetSiteStats(ctx context.Context) (GetSiteStatsRow, error) {
	row := q.db.QueryRow(ctx, getSiteStats)
	var i GetSiteStatsRow
	err := row.Scan(
		&i.TotalUsers,
		&i.UsersToday,
		&i.UsersThisWeek,
		&i.TotalStories,
		&i.StoriesToday,
		&i.StoriesThisWeek,
		&i.TotalComments,
		&i.CommentsToday,
		&i.CommentsThisWeek,
		&i.ActiveUsersToday,
		&i.ActiveUsersThisWeek,
	)
	return i, err
}
