// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: stories.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countStories = `-- name: CountStories :one
SELECT count(*) FROM stories WHERE deleted_at IS NULL
`

func (q *Queries) CountStories(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countStories)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createStory = `-- name: CreateStory :one
INSERT INTO stories (user_id, domain_id, origin_id, url, normalized_url, title, body, short_code)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, user_id, domain_id, origin_id, url, normalized_url, title, body, short_code, created_at, updated_at, deleted_at
`

type CreateStoryParams struct {
	UserID        int64
	DomainID      pgtype.Int8
	OriginID      pgtype.Int8
	Url           pgtype.Text
	NormalizedUrl pgtype.Text
	Title         string
	Body          pgtype.Text
	ShortCode     string
}

type CreateStoryRow struct {
	ID            int64
	UserID        int64
	DomainID      pgtype.Int8
	OriginID      pgtype.Int8
	Url           pgtype.Text
	NormalizedUrl pgtype.Text
	Title         string
	Body          pgtype.Text
	ShortCode     string
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
	DeletedAt     pgtype.Timestamptz
}

func (q *Queries) CreateStory(ctx context.Context, arg CreateStoryParams) (CreateStoryRow, error) {
	row := q.db.QueryRow(ctx, createStory,
		arg.UserID,
		arg.DomainID,
		arg.OriginID,
		arg.Url,
		arg.NormalizedUrl,
		arg.Title,
		arg.Body,
		arg.ShortCode,
	)
	var i CreateStoryRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DomainID,
		&i.OriginID,
		&i.Url,
		&i.NormalizedUrl,
		&i.Title,
		&i.Body,
		&i.ShortCode,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createTagging = `-- name: CreateTagging :exec
INSERT INTO taggings (story_id, tag_id)
VALUES ($1, $2)
`

type CreateTaggingParams struct {
	StoryID int64
	TagID   int64
}

func (q *Queries) CreateTagging(ctx context.Context, arg CreateTaggingParams) error {
	_, err := q.db.Exec(ctx, createTagging, arg.StoryID, arg.TagID)
	return err
}

const deleteTaggingsByStory = `-- name: DeleteTaggingsByStory :exec
DELETE FROM taggings WHERE story_id = $1
`

func (q *Queries) DeleteTaggingsByStory(ctx context.Context, storyID int64) error {
	_, err := q.db.Exec(ctx, deleteTaggingsByStory, storyID)
	return err
}

const findRecentByNormalizedURL = `-- name: FindRecentByNormalizedURL :one
SELECT id, url, title, short_code, created_at
FROM stories
WHERE normalized_url = $1
  AND deleted_at IS NULL
  AND created_at > now() - INTERVAL '30 days'
ORDER BY created_at DESC
LIMIT 1
`

type FindRecentByNormalizedURLRow struct {
	ID        int64
	Url       pgtype.Text
	Title     string
	ShortCode string
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) FindRecentByNormalizedURL(ctx context.Context, normalizedUrl pgtype.Text) (FindRecentByNormalizedURLRow, error) {
	row := q.db.QueryRow(ctx, findRecentByNormalizedURL, normalizedUrl)
	var i FindRecentByNormalizedURLRow
	err := row.Scan(
		&i.ID,
		&i.Url,
		&i.Title,
		&i.ShortCode,
		&i.CreatedAt,
	)
	return i, err
}

const getStory = `-- name: GetStory :one
SELECT
    s.id,
    s.user_id,
    s.url,
    s.title,
    s.body,
    s.short_code,
    s.upvotes,
    s.downvotes,
    s.comment_count,
    s.created_at,
    s.deleted_at,
    u.username,
    d.domain,
    o.origin
FROM stories AS s
JOIN users AS u ON u.id = s.user_id
LEFT JOIN domains AS d ON d.id = s.domain_id
LEFT JOIN origins AS o ON o.id = s.origin_id
WHERE ($1::bigint IS NULL OR s.id = $1)
  AND ($2::text IS NULL OR s.short_code = $2)
`

type GetStoryParams struct {
	ID        pgtype.Int8
	ShortCode pgtype.Text
}

type GetStoryRow struct {
	ID           int64
	UserID       int64
	Url          pgtype.Text
	Title        string
	Body         pgtype.Text
	ShortCode    string
	Upvotes      int32
	Downvotes    int32
	CommentCount int32
	CreatedAt    pgtype.Timestamptz
	DeletedAt    pgtype.Timestamptz
	Username     string
	Domain       pgtype.Text
	Origin       pgtype.Text
}

func (q *Queries) GetStory(ctx context.Context, arg GetStoryParams) (GetStoryRow, error) {
	row := q.db.QueryRow(ctx, getStory, arg.ID, arg.ShortCode)
	var i GetStoryRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Url,
		&i.Title,
		&i.Body,
		&i.ShortCode,
		&i.Upvotes,
		&i.Downvotes,
		&i.CommentCount,
		&i.CreatedAt,
		&i.DeletedAt,
		&i.Username,
		&i.Domain,
		&i.Origin,
	)
	return i, err
}

const getStoryTags = `-- name: GetStoryTags :many
SELECT t.id, t.tag, t.is_media, t.hotness_mod
FROM taggings AS tg
JOIN tags AS t ON t.id = tg.tag_id
WHERE tg.story_id = $1
ORDER BY t.is_media DESC, t.tag ASC
`

type GetStoryTagsRow struct {
	ID         int64
	Tag        string
	IsMedia    bool
	HotnessMod float64
}

func (q *Queries) GetStoryTags(ctx context.Context, storyID int64) ([]GetStoryTagsRow, error) {
	rows, err := q.db.Query(ctx, getStoryTags, storyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetStoryTagsRow
	for rows.Next() {
		var i GetStoryTagsRow
		if err := rows.Scan(
			&i.ID,
			&i.Tag,
			&i.IsMedia,
			&i.HotnessMod,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTagsByNames = `-- name: GetTagsByNames :many
SELECT id, tag, description, category_id, privileged, is_media, active, hotness_mod, created_at, updated_at
FROM tags
WHERE lower(tag) = ANY($1::text[])
  AND active = true
`

func (q *Queries) GetTagsByNames(ctx context.Context, names []string) ([]Tag, error) {
	rows, err := q.db.Query(ctx, getTagsByNames, names)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tag
	for rows.Next() {
		var i Tag
		if err := rows.Scan(
			&i.ID,
			&i.Tag,
			&i.Description,
			&i.CategoryID,
			&i.Privileged,
			&i.IsMedia,
			&i.Active,
			&i.HotnessMod,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStories = `-- name: ListStories :many
SELECT
    s.id,
    s.url,
    s.title,
    s.body,
    s.short_code,
    s.upvotes,
    s.downvotes,
    s.comment_count,
    s.created_at,
    s.deleted_at,
    u.username,
    d.domain,
    o.origin
FROM stories AS s
JOIN users AS u ON u.id = s.user_id
LEFT JOIN domains AS d ON d.id = s.domain_id
LEFT JOIN origins AS o ON o.id = s.origin_id
LEFT JOIN taggings AS tg ON tg.story_id = s.id AND tg.tag_id = $1
WHERE
    ($1::bigint IS NULL OR tg.tag_id IS NOT NULL)
    AND ($2::text IS NULL OR lower(u.username) = lower($2))
    AND (NOT $3::bool OR s.deleted_at IS NULL)
    AND s.id NOT IN (
        SELECT tg2.story_id FROM taggings AS tg2
        WHERE tg2.tag_id = ANY($4::bigint[])
    )
ORDER BY s.created_at DESC
LIMIT $5
`

type ListStoriesParams struct {
	TagID        pgtype.Int8
	Username     pgtype.Text
	HideDeleted  bool
	HiddenTagIds []int64
	StoryLimit   int32
}

type ListStoriesRow struct {
	ID           int64
	Url          pgtype.Text
	Title        string
	Body         pgtype.Text
	ShortCode    string
	Upvotes      int32
	Downvotes    int32
	CommentCount int32
	CreatedAt    pgtype.Timestamptz
	DeletedAt    pgtype.Timestamptz
	Username     string
	Domain       pgtype.Text
	Origin       pgtype.Text
}

func (q *Queries) ListStories(ctx context.Context, arg ListStoriesParams) ([]ListStoriesRow, error) {
	rows, err := q.db.Query(ctx, listStories,
		arg.TagID,
		arg.Username,
		arg.HideDeleted,
		arg.HiddenTagIds,
		arg.StoryLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListStoriesRow
	for rows.Next() {
		var i ListStoriesRow
		if err := rows.Scan(
			&i.ID,
			&i.Url,
			&i.Title,
			&i.Body,
			&i.ShortCode,
			&i.Upvotes,
			&i.Downvotes,
			&i.CommentCount,
			&i.CreatedAt,
			&i.DeletedAt,
			&i.Username,
			&i.Domain,
			&i.Origin,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recalculateStoryScores = `-- name: RecalculateStoryScores :execrows
UPDATE stories SET
  upvotes = coalesce(v.cnt, 0)::int,
  downvotes = coalesce(hf.cnt, 0)::int
FROM stories s2
LEFT JOIN (SELECT story_id, count(*) AS cnt FROM votes GROUP BY story_id) v ON v.story_id = s2.id
LEFT JOIN (
    SELECT hs.story_id, count(*) AS cnt
    FROM hidden_stories hs
    JOIN story_flags sf ON sf.user_id = hs.user_id AND sf.story_id = hs.story_id
    WHERE NOT EXISTS (
        SELECT 1 FROM comments c
        WHERE c.story_id = hs.story_id AND c.user_id = hs.user_id AND c.deleted_at IS NULL
    )
    GROUP BY hs.story_id
) hf ON hf.story_id = s2.id
WHERE stories.id = s2.id
`

func (q *Queries) RecalculateStoryScores(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, recalculateStoryScores)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setStoryUpvotes = `-- name: SetStoryUpvotes :exec
UPDATE stories SET upvotes = $1 WHERE id = $2
`

type SetStoryUpvotesParams struct {
	Upvotes int32
	ID      int64
}

func (q *Queries) SetStoryUpvotes(ctx context.Context, arg SetStoryUpvotesParams) error {
	_, err := q.db.Exec(ctx, setStoryUpvotes, arg.Upvotes, arg.ID)
	return err
}

const softDeleteStory = `-- name: SoftDeleteStory :exec
UPDATE stories SET deleted_at = now(), updated_at = now() WHERE id = $1
`

func (q *Queries) SoftDeleteStory(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, softDeleteStory, id)
	return err
}

const updateStoryBody = `-- name: UpdateStoryBody :exec
UPDATE stories SET body = $1, updated_at = now() WHERE id = $2
`

type UpdateStoryBodyParams struct {
	Body pgtype.Text
	ID   int64
}

func (q *Queries) UpdateStoryBody(ctx context.Context, arg UpdateStoryBodyParams) error {
	_, err := q.db.Exec(ctx, updateStoryBody, arg.Body, arg.ID)
	return err
}

const updateStoryTitle = `-- name: UpdateStoryTitle :exec
UPDATE stories SET title = $1, updated_at = now() WHERE id = $2
`

type UpdateStoryTitleParams struct {
	Title string
	ID    int64
}

func (q *Queries) UpdateStoryTitle(ctx context.Context, arg UpdateStoryTitleParams) error {
	_, err := q.db.Exec(ctx, updateStoryTitle, arg.Title, arg.ID)
	return err
}

const updateStoryURL = `-- name: UpdateStoryURL :exec
UPDATE stories SET url = $1, normalized_url = $2, domain_id = $3, origin_id = $4, updated_at = now() WHERE id = $5
`

type UpdateStoryURLParams struct {
	Url           pgtype.Text
	NormalizedUrl pgtype.Text
	DomainID      pgtype.Int8
	OriginID      pgtype.Int8
	ID            int64
}

func (q *Queries) UpdateStoryURL(ctx context.Context, arg UpdateStoryURLParams) error {
	_, err := q.db.Exec(ctx, updateStoryURL,
		arg.Url,
		arg.NormalizedUrl,
		arg.DomainID,
		arg.OriginID,
		arg.ID,
	)
	return err
}
