// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tags.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCategory = `-- name: CreateCategory :one
INSERT INTO categories (name)
VALUES ($1)
RETURNING id, name, created_at, updated_at
`

func (q *Queries) CreateCategory(ctx context.Context, name string) (Category, error) {
	row := q.db.QueryRow(ctx, createCategory, name)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCategoryByName = `-- name: GetCategoryByName :one
SELECT id, name, created_at, updated_at
FROM categories
WHERE lower(name) = lower($1)
LIMIT 1
`

func (q *Queries) GetCategoryByName(ctx context.Context, name string) (Category, error) {
	row := q.db.QueryRow(ctx, getCategoryByName, name)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTagByName = `-- name: GetTagByName :one
SELECT id, tag, description, category_id, privileged, is_media, active, hotness_mod, created_at, updated_at
FROM tags
WHERE lower(tag) = lower($1)
  AND active = true
LIMIT 1
`

func (q *Queries) GetTagByName(ctx context.Context, tag string) (Tag, error) {
	row := q.db.QueryRow(ctx, getTagByName, tag)
	var i Tag
	err := row.Scan(
		&i.ID,
		&i.Tag,
		&i.Description,
		&i.CategoryID,
		&i.Privileged,
		&i.IsMedia,
		&i.Active,
		&i.HotnessMod,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTagsByIDs = `-- name: GetTagsByIDs :many
SELECT id, tag, description, category_id, privileged, is_media, active, hotness_mod, created_at, updated_at
FROM tags
WHERE id = ANY($1::bigint[])
  AND active = true
`

func (q *Queries) GetTagsByIDs(ctx context.Context, ids []int64) ([]Tag, error) {
	rows, err := q.db.Query(ctx, getTagsByIDs, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tag
	for rows.Next() {
		var i Tag
		if err := rows.Scan(
			&i.ID,
			&i.Tag,
			&i.Description,
			&i.CategoryID,
			&i.Privileged,
			&i.IsMedia,
			&i.Active,
			&i.HotnessMod,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActiveTags = `-- name: ListActiveTags :many
SELECT id, tag, description, category_id, privileged, is_media, active, hotness_mod, created_at, updated_at
FROM tags
WHERE active = true
ORDER BY is_media DESC, tag ASC
`

func (q *Queries) ListActiveTags(ctx context.Context) ([]Tag, error) {
	rows, err := q.db.Query(ctx, listActiveTags)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tag
	for rows.Next() {
		var i Tag
		if err := rows.Scan(
			&i.ID,
			&i.Tag,
			&i.Description,
			&i.CategoryID,
			&i.Privileged,
			&i.IsMedia,
			&i.Active,
			&i.HotnessMod,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActiveTagsWithCategory = `-- name: ListActiveTagsWithCategory :many
SELECT t.id, t.tag, t.description, t.category_id, t.privileged, t.is_media,
       COALESCE(c.name, '') AS category_name
FROM tags t
LEFT JOIN categories c ON c.id = t.category_id
WHERE t.active = true
ORDER BY category_name, t.tag
`

type ListActiveTagsWithCategoryRow struct {
	ID           int64
	Tag          string
	Description  string
	CategoryID   pgtype.Int8
	Privileged   bool
	IsMedia      bool
	CategoryName string
}

func (q *Queries) ListActiveTagsWithCategory(ctx context.Context) ([]ListActiveTagsWithCategoryRow, error) {
	rows, err := q.db.Query(ctx, listActiveTagsWithCategory)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActiveTagsWithCategoryRow
	for rows.Next() {
		var i ListActiveTagsWithCategoryRow
		if err := rows.Scan(
			&i.ID,
			&i.Tag,
			&i.Description,
			&i.CategoryID,
			&i.Privileged,
			&i.IsMedia,
			&i.CategoryName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertTag = `-- name: UpsertTag :exec
INSERT INTO tags (tag, description, category_id, privileged, is_media)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT ((lower(tag)))
DO UPDATE SET
  description = EXCLUDED.description,
  category_id = EXCLUDED.category_id,
  privileged = EXCLUDED.privileged,
  is_media = EXCLUDED.is_media,
  active = true,
  updated_at = now()
`

type UpsertTagParams struct {
	Tag         string
	Description string
	CategoryID  pgtype.Int8
	Privileged  bool
	IsMedia     bool
}

func (q *Queries) UpsertTag(ctx context.Context, arg UpsertTagParams) error {
	_, err := q.db.Exec(ctx, upsertTag,
		arg.Tag,
		arg.Description,
		arg.CategoryID,
		arg.Privileged,
		arg.IsMedia,
	)
	return err
}
