// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user_ips.sql

package store

import (
	"context"
)

const getIPsByUserID = `-- name: GetIPsByUserID :many
SELECT id, user_id, ip_address, action, first_seen_at, last_seen_at, hit_count FROM user_ips WHERE user_id = $1 ORDER BY last_seen_at DESC
`

func (q *Queries) GetIPsByUserID(ctx context.Context, userID int64) ([]UserIp, error) {
	rows, err := q.db.Query(ctx, getIPsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserIp
	for rows.Next() {
		var i UserIp
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.IpAddress,
			&i.Action,
			&i.FirstSeenAt,
			&i.LastSeenAt,
			&i.HitCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUsersByIP = `-- name: GetUsersByIP :many
SELECT id, user_id, ip_address, action, first_seen_at, last_seen_at, hit_count FROM user_ips WHERE ip_address = $1 ORDER BY last_seen_at DESC
`

func (q *Queries) GetUsersByIP(ctx context.Context, ipAddress string) ([]UserIp, error) {
	rows, err := q.db.Query(ctx, getUsersByIP, ipAddress)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserIp
	for rows.Next() {
		var i UserIp
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.IpAddress,
			&i.Action,
			&i.FirstSeenAt,
			&i.LastSeenAt,
			&i.HitCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertUserIP = `-- name: UpsertUserIP :exec
INSERT INTO user_ips (user_id, ip_address, action)
VALUES ($1, $2, $3)
ON CONFLICT (user_id, ip_address, action)
DO UPDATE SET last_seen_at = now(), hit_count = user_ips.hit_count + 1
`

type UpsertUserIPParams struct {
	UserID    int64
	IpAddress string
	Action    string
}

func (q *Queries) UpsertUserIP(ctx context.Context, arg UpsertUserIPParams) error {
	_, err := q.db.Exec(ctx, upsertUserIP, arg.UserID, arg.IpAddress, arg.Action)
	return err
}
